services:
  - type: web
    name: fastapi-socket-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker socket_server:app
    autoDeploy: true
